- name: Configure docker in new EC2 ubuntu Machine
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: updating the New Ec2 Machine
      command: sudo apt update
    - name: install required dependency
      apt:
        name: '{{item}}'
        state: present
        update_cache: 'yes'
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: add GPG key
      apt_key:
        url: 'https://download.docker.com/linux/ubuntu/gpg'
        state: present
    - name: add docker repository to apt
      apt_repository:
        repo: 'deb https://download.docker.com/linux/ubuntu bionic stable'
        state: present
    - name: install docker items
      become: yes
      become_user: root
      apt:
        name: '{{item}}'
        state: latest
        update_cache: 'yes'
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: Check docker service started
      become: yes
      become_user: root
      service:
        name: docker
        state: started
        enabled: 'yes'
    - name: Deploy the Image and Run as Container
      command: 'docker run -itd -p 8084:8081 unknowndocker811/insurance-app:1.0'
